### ISSUE TITLE
The ongoing logo fail checklist

### ISSUE THREAD

**Issue by HarmenM** [ScientaNL/brandr-api#44]
# Malformed SVG
- [ ] https://brandr.app/

# No image
- [ ] https://www.tui.nl/vliegtickets/overons/
- [ ] www.indeed.nl

# Wrong image
- [ ] https://www.tuincentrum.nl/bomen
- [ ] http://www.bpmsystemen.nl/
